import "@/styles/globals.css";
import type { Metadata } from "next";
import Navigation from "@/components/navigation";

export const metadata: Metadata = {
  title: {
    template: "%s | Next News App",
    default: "Next News App",
  },
  description: "Generated by Yeonhyeok Kim",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
